name: .NET Console CI

on:
  push:
    branches: [master]
    paths:
      - './scr/**'
  pull_request:
    branches: [master]
    paths:
      - './scr/**'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./scr/myapp/myapp.csproj

      - name: Build project
        run: dotnet build --configuration Release ./scr/myapp/myapp.csproj

      - name: Run myapp
        run: dotnet run --configuration Release --project ./scr/myapp/myapp.csproj